apiVersion: apps/v1
kind: Deployment
metadata:
  name: waystar-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waystar-demo
  template:
    metadata:
      labels:
        app: waystar-demo
    spec:
      containers:
        - name: waystar-demo
          image: ghcr.io/breelatimer/waystar-demo:latest
          ports:
            - containerPort: 8080